### ISSUE TITLE
[Question] Hi, developer..

### ISSUE THREAD

**Issue by juandisay** [Templum/rabbitmq-connector#63] opened 2021-01-19 08:56 UTC
**How it works?**
Hi, Can you help me, how to this connector work?
Do you have any blog or video tutorial for this?
Thank so much.

**Comment by Templum** [comment] 2021-01-19 16:13
Hello @juandisay ,

There is no such thing. Please have a look at the usage section of the readme to learn how it functions. If you have issues with deployment please check out the relevant sections.

If there is something concrete feel free to answer it here, but please provide some details on the infrastructure etc.

Best regards

**Comment by juandisay** [comment] 2021-01-20 00:26
I have producer code , but cannot connect.
I built it simple producer with Python Pika 

`import json
import random
import pika

print('pika version: %s' % pika.__version__)

topic = "account"

connection =  pika.BlockingConnection(
	pika.ConnectionParameters("docker.local",5672,"/"))

main_channel = connection.channel()

main_channel.queue_declare("OpenFaasQueue", exclusive=True)
main_channel.exchange_declare(
    exchange='OpenFaasEx', exchange_type='topic')


main_channel.basic_publish(
	exchange='OpenFaasEx',
	routing_key=topic,
	body="bunga",
	properties=pika.BasicProperties(content_type='text/plain'))
    
connection.close()`

Do you have input for me, please

**Comment by Templum** [comment] 2021-01-20 12:16
Can you tell me on which platform you are running it (swarm / k8s / locally)?

In which order did you start producer & consumer?

Please share also the logs, as from what you shared alone nothing really can be said

**Comment by juandisay** [comment] 2021-01-20 14:22
Now, My project run in swarm Local just for dev, for production, running it k8s.
I really don't understand, how to implement this connector, I don't understand the go programming language.
But I tried to implement following what is documented, and still can't.
I hope this is like the ingress operator.

```
func_connector.1.x591qinksw4p@node1    | 2021/01/20 14:17:36 Update cache with 0 entries
func_connector.1.x591qinksw4p@node1    | 2021/01/20 14:17:43 Finished invocations of functions on topic figlet
func_connector.1.x591qinksw4p@node1    | 2021/01/20 14:17:48 Finished invocations of functions on topic figlet
func_connector.1.x591qinksw4p@node1    | 2021/01/20 14:18:03 Finished invocations of functions on topic figlet
func_connector.1.x591qinksw4p@node1    | 2021/01/20 14:18:06 Crawling for functions
func_connector.1.x591qinksw4p@node1    | 2021/01/20 14:18:06 Crawling finished will now refresh the cache
func_connector.1.x591qinksw4p@node1    | 2021/01/20 14:18:06 Update cache with 0 entries
func_connector.1.x591qinksw4p@node1    | 2021/01/20 14:18:36 Crawling for functions
func_connector.1.x591qinksw4p@node1    | 2021/01/20 14:18:36 Crawling finished will now refresh the cache
func_connector.1.x591qinksw4p@node1    | 2021/01/20 14:18:36 Update cache with 0 entries
func_connector.1.x591qinksw4p@node1    | 2021/01/20 14:19:04 Finished invocations of functions on topic figlet
func_connector.1.x591qinksw4p@node1    | 2021/01/20 14:19:06 Crawling for functions
func_connector.1.x591qinksw4p@node1    | 2021/01/20 14:19:06 Crawling finished will now refresh the cache
func_connector.1.x591qinksw4p@node1    | 2021/01/20 14:19:06 Update cache with 0 entries
func_connector.1.x591qinksw4p@node1    | 2021/01/20 14:19:36 Crawling for functions
func_connector.1.x591qinksw4p@node1    | 2021/01/20 14:19:36 Crawling finished will now refresh the cache
func_connector.1.x591qinksw4p@node1    | 2021/01/20 14:19:36 Update cache with 0 entries
func_connector.1.x591qinksw4p@node1    | 2021/01/20 14:19:55 Finished invocations of functions on topic figlet
func_connector.1.x591qinksw4p@node1    | 2021/01/20 14:20:06 Crawling for functions
func_connector.1.x591qinksw4p@node1    | 2021/01/20 14:20:06 Crawling finished will now refresh the cache
func_connector.1.x591qinksw4p@node1    | 2021/01/20 14:20:06 Update cache with 0 entries
func_connector.1.x591qinksw4p@node1    | 2021/01/20 14:20:16 Finished invocations of functions on topic figlet
func_connector.1.x591qinksw4p@node1    | 2021/01/20 14:20:36 Crawling for functions
func_connector.1.x591qinksw4p@node1    | 2021/01/20 14:20:36 Crawling finished will now refresh the cache
func_connector.1.x591qinksw4p@node1    | 2021/01/20 14:20:36 Update cache with 0 entries
func_connector.1.x591qinksw4p@node1    | 2021/01/20 14:20:40 Finished invocations of functions on topic figlet
func_connector.1.x591qinksw4p@node1    | 2021/01/20 14:20:51 Finished invocations of functions on topic figlet
func_connector.1.x591qinksw4p@node1    | 2021/01/20 14:21:06 Crawling for functions
func_connector.1.x591qinksw4p@node1    | 2021/01/20 14:21:06 Crawling finished will now refresh the cache
func_connector.1.x591qinksw4p@node1    | 2021/01/20 14:21:06 Update cache with 0 entries
```

**Comment by Templum** [comment] 2021-01-20 15:22
@juandisay thanks for sharing the information. As visible from your logs the setup seems to be correct and it logs invocations, however also visible from your logs is that the lambda might be not deployed with the correct annotation/topic.

Here is an example of creating a function with annotation + topic: `$ faas-cli store deploy figlet --annotation topic="account"`. You would need to replace `account` with your topic (seems to be) `figlet`.

Also wanted to highlight the connector only does fire & forget, so the outcome of the invocation is not streamed back. So one way for you would be to check the invocation count (should go up) or check the logs of the function itself.

**Comment by juandisay** [comment] 2021-01-20 15:40
PRODUCER
```
# -*- coding: utf-8 -*-
# pylint: disable=C0111,C0103,R0205

import json
import random
import pika

print('pika version: %s' % pika.__version__)

topic = "account"

connection =  pika.BlockingConnection(
	pika.ConnectionParameters("docker.local",5672,"/"))

main_channel = connection.channel()

main_channel.exchange_declare(
        exchange='OpenFaasEx',
        exchange_type='direct',
        passive=False,
        durable=True,
        auto_delete=False)

main_channel.queue_declare(
	queue="OpenFaaS_account",
        passive=False,
        durable=True,
        auto_delete=False)

main_channel.basic_publish(
	exchange='OpenFaasEx',
	routing_key=topic,
	body="foosyaa",
	properties=pika.BasicProperties(content_type='text/plain'))
    
connection.close()
```
CONSUME
```
import pika 

topic = "account"

connection =  pika.BlockingConnection(
	pika.ConnectionParameters("docker.local",5672,"/")
)

channel = connection.channel()

channel.exchange_declare(
        exchange='OpenFaasEx',
        exchange_type='direct',
        passive=False,
        durable=True,
        auto_delete=False)

channel.queue_declare(
	    queue="OpenFaaS_account",
        passive=False,
        durable=True,
        auto_delete=False)

channel.queue_bind(
    exchange='OpenFaasEx', queue="OpenFaaS_account", routing_key=topic)

def callback(ch, method, properties, body):
	print("[x] message received %s %s" % (method.routing_key,body))

channel.basic_consume(
	 queue="OpenFaaS_account", on_message_callback=callback, auto_ack=True)

print("[x] waiting")

channel.start_consuming()
```
Yes , I think connector not connect with function, so invocation is not streamed back.
![not_connect](https://user-images.githubusercontent.com/9843141/105198152-eff15480-5b6f-11eb-8464-431139e70f8b.gif)

hm, I replace My topic to `account`
`faas store deploy figlet --annotation topic="account" -g $IP`

**Comment by Templum** [comment] 2021-01-20 15:45
Can you see the annotation in the swarm information for the function?

I believe the issue is more with the connector not being able to discover the function.

**Comment by juandisay** [comment] 2021-01-20 16:01
Exactly, the connector not being able to discover the function.
about annotation on swarm information, You mean like service inspect ?
```
[
    {
        "ID": "nq9xmr93u2rmjteee1qw9vl4g",
        "Version": {
            "Index": 5291
        },
        "CreatedAt": "2021-01-20T14:57:53.194517973Z",
        "UpdatedAt": "2021-01-20T15:27:25.937042613Z",
        "Spec": {
            "Name": "figlet",
            "Labels": {
                "com.openfaas.function": "figlet",
                "function": "true"
            },
            "TaskTemplate": {
                "ContainerSpec": {
                    "Image": "functions/figlet:0.13.0",
                    "Labels": {
                        "com.openfaas.function": "figlet",
                        "com.openfaas.uid": "534022283",
                        "function": "true"
                    },
                    "Env": [
                        "fprocess=figlet"
                    ],
                    "StopGracePeriod": 10000000000,
                    "DNSConfig": {},
                    "Isolation": "default"
                },
                "Resources": {},
                "RestartPolicy": {
                    "Condition": "any",
                    "Delay": 5000000000,
                    "MaxAttempts": 5
                },
                "Placement": {
                    "Constraints": [
                        "node.platform.os == linux"
                    ]
                },
                "Networks": [
                    {
                        "Target": "0k3q2qpxg021uyvikpiwnehih"
                    }
                ],
                "ForceUpdate": 0,
                "Runtime": "container"
            },
            "Mode": {
                "Replicated": {
                    "Replicas": 1
                }
            },
            "UpdateConfig": {
                "Parallelism": 1,
                "FailureAction": "rollback",
                "Monitor": 5000000000,
                "MaxFailureRatio": 0,
                "Order": "start-first"
            },
            "RollbackConfig": {
                "Parallelism": 0,
                "FailureAction": "pause",
                "Monitor": 5000000000,
                "MaxFailureRatio": 0,
                "Order": "stop-first"
            }
        },
        "PreviousSpec": {
            "Name": "figlet",
            "Labels": {
                "com.openfaas.function": "figlet",
                "function": "true"
            },
            "TaskTemplate": {
                "ContainerSpec": {
                    "Image": "functions/figlet:0.13.0",
                    "Labels": {
                        "com.openfaas.function": "figlet",
                        "com.openfaas.uid": "527760587",
                        "function": "true"
                    },
                    "Env": [
                        "fprocess=figlet"
                    ],
                    "StopGracePeriod": 10000000000,
                    "DNSConfig": {},
                    "Isolation": "default"
                },
                "RestartPolicy": {
                    "Condition": "any",
                    "Delay": 5000000000,
                    "MaxAttempts": 5
                },
                "Placement": {
                    "Constraints": [
                        "node.platform.os == linux"
                    ]
                },
                "Networks": [
                    {
                        "Target": "0k3q2qpxg021uyvikpiwnehih"
                    }
                ],
                "ForceUpdate": 0,
                "Runtime": "container"
            },
            "Mode": {
                "Replicated": {
                    "Replicas": 1
                }
            },
            "UpdateConfig": {
                "Parallelism": 1,
                "FailureAction": "rollback",
                "MaxFailureRatio": 0,
                "Order": "start-first"
            },
            "RollbackConfig": {
                "Parallelism": 0,
                "FailureAction": "pause",
                "MaxFailureRatio": 0,
                "Order": "stop-first"
            }
        },
        "Endpoint": {
            "Spec": {},
            "VirtualIPs": [
                {
                    "NetworkID": "0k3q2qpxg021uyvikpiwnehih",
                    "Addr": "10.0.3.33/24"
                }
            ]
        },
        "UpdateStatus": {
            "State": "completed",
            "StartedAt": "2021-01-20T15:27:09.542017123Z",
            "CompletedAt": "2021-01-20T15:27:25.937022529Z",
            "Message": "update completed"
        }
    }
]

```

**Comment by Templum** [comment] 2021-01-20 16:32
From what you shared this seems to be an issue with OpenFaaS not posting the annotation.

You can try to call the OpenFaaS Endpoint `/system/functions` and check if there it shares the annotation. Because the connector gets it directly from OpenFaaS Endpoint (see [here](https://github.com/Templum/rabbitmq-connector/blob/178c2281c40e6b2f53bb775a57d04c6b62dbedc2/pkg/openfaas/cacher.go#L109-L120)).

It's a long time since I worked with Swarm, but I know that the setup worked. As this was my personal way of testing it.

**Comment by juandisay** [comment] 2021-01-20 16:36
```
[
  {
    "name": "figlet",
    "image": "functions/figlet:0.13.0",
    "invocationCount": 8,
    "replicas": 1,
    "envProcess": "figlet",
    "availableReplicas": 0,
    "labels": {
      "com.openfaas.function": "figlet",
      "function": "true"
    },
    "annotations": null
  }
]
```
yeps, annotations is Null.. HOw to create topic?

**Comment by Templum** [comment] 2021-01-20 16:44
Honestly no idea, from the code of the CLI annotation flag is the correct one.

Maybe swarm dropped support for it

**Comment by juandisay** [comment] 2021-01-20 16:55
yes openfaas was not support swarm, But swarm very easy to create image docker just for built and work in local. 
Reduce push image to registry :) 
I used openfaas previous version ., so I can install openfaas with swarm.

Okay @Templum thank so much for support :+1: :+1: 
I think, I can try in k8s  :)

**Comment by juandisay** [comment] 2021-01-21 01:08
![succes](https://user-images.githubusercontent.com/9843141/105259851-2efac680-5bbf-11eb-9351-b1ca51e1d01d.gif)

@Templum now its works. :)
Am Reinstall my openfaas, with new version :1st_place_medal:  like 
openfaas  checkout 0.18.0

But my question is
How to get the response mean Invoked result??

**Comment by Templum** [comment] 2021-01-21 07:12
@juandisay sadly getting the response is not yet implemented

**Comment by juandisay** [comment] 2021-01-21 07:43
> @juandisay sadly getting the response is not yet implemented

okay. Thanks so much for support :+1: :+1:

**Comment by Templum** [comment] 2021-01-21 14:15
You are welcome, I will now close the issue. Please feel free to recreate if needed.

**Closed by Templum** 2021-01-21 14:15 UTC
Labels: question
