### ISSUE TITLE
Error Pod Reading messages

### ISSUE THREAD

**Issue by rafaelnicolett** [Templum/rabbitmq-connector#12] opened 2018-12-07 15:30 UTC
I have the problem that my pod it's restart every time.

2018/12/07 15:26:15 [*] Waiting for messages. To exit press CTRL+C
2018/12/07 15:26:45 invalid character 'i' looking for beginning of value

Any suggestion?

**Comment by Templum** [comment] 2018-12-07 17:23
First of all which version are you using, is this an older version? 

I saw similar issues when you ran the connector and tried to connect to a basic auth protected OpenFaaS Gateway (Currently the standard). In that case you want to configure Basic Auth correctly, by setting the environment variables

**Comment by Templum** [comment] 2018-12-20 19:46
Will close this now, if you still experience the issues, feel free to reopen.

**Comment by kumy** [comment] 2019-01-19 14:11
@Templum I also encounter this issue with either `release` or `develop` tags

```
2019/01/19 14:09:37 OpenFaaS RabbitMQ Connector [Version: dev Commit: local]
&{0xc00005ad20 0xc00000a3a0 0xc00000eca0 0xc00000a380}
2019/01/19 14:09:37 Starting Init Process of Connector
2019/01/19 14:09:37 Successfully established connection with rabbit:5672/
2019/01/19 14:09:37 1 Topics are registered. Will be spawning 8 Workers per Topic. 
2019/01/19 14:09:37 Connector finished Init Process and is now running
2019/01/19 14:09:37 Starting Init Process of Worker gifted_keller6 for topic geokrety.geokret.insert
2019/01/19 14:09:37 Starting Init Process of Worker vigilant_borg0 for topic geokrety.geokret.insert
2019/01/19 14:09:37 Starting Init Process of Worker gracious_curie6 for topic geokrety.geokret.insert
2019/01/19 14:09:37 Starting Init Process of Worker brave_hamilton2 for topic geokrety.geokret.insert
2019/01/19 14:09:37 Starting Init Process of Worker determined_leavitt0 for topic geokrety.geokret.insert
2019/01/19 14:09:37 Starting Init Process of Worker silly_liskov3 for topic geokrety.geokret.insert
2019/01/19 14:09:37 Starting Init Process of Worker infallible_euclid0 for topic geokrety.geokret.insert
2019/01/19 14:09:37 Starting Init Process of Worker hardcore_perlman2 for topic geokrety.geokret.insert
2019/01/19 14:09:37  [*] Waiting for messages. To exit press CTRL+C
2019/01/19 14:09:37 Binding Queue geokrety to Exchange geokrety for Topic: geokrety.geokret.insert
2019/01/19 14:09:37 Binding Queue geokrety to Exchange geokrety for Topic: geokrety.geokret.insert
2019/01/19 14:09:37 Binding Queue geokrety to Exchange geokrety for Topic: geokrety.geokret.insert
2019/01/19 14:09:37 Binding Queue geokrety to Exchange geokrety for Topic: geokrety.geokret.insert
2019/01/19 14:09:37 Binding Queue geokrety to Exchange geokrety for Topic: geokrety.geokret.insert
2019/01/19 14:09:37 Binding Queue geokrety to Exchange geokrety for Topic: geokrety.geokret.insert
2019/01/19 14:09:37 Binding Queue geokrety to Exchange geokrety for Topic: geokrety.geokret.insert
2019/01/19 14:09:37 Binding Queue geokrety to Exchange geokrety for Topic: geokrety.geokret.insert
2019/01/19 14:09:37 Worker vigilant_borg0 started consuming messages for geokrety.geokret.insert
2019/01/19 14:09:37 Worker brave_hamilton2 started consuming messages for geokrety.geokret.insert
2019/01/19 14:09:37 Worker hardcore_perlman2 started consuming messages for geokrety.geokret.insert
2019/01/19 14:09:37 Worker gracious_curie6 started consuming messages for geokrety.geokret.insert
2019/01/19 14:09:37 Worker determined_leavitt0 started consuming messages for geokrety.geokret.insert
2019/01/19 14:09:37 Worker infallible_euclid0 started consuming messages for geokrety.geokret.insert
2019/01/19 14:09:37 Worker silly_liskov3 started consuming messages for geokrety.geokret.insert
2019/01/19 14:09:37 Worker gifted_keller6 started consuming messages for geokrety.geokret.insert
2019/01/19 14:10:07 invalid character 'i' looking for beginning of value
2019/01/19 14:10:15 OpenFaaS RabbitMQ Connector [Version: dev Commit: local]
&{0xc00005ad20 0xc00000a3a0 0xc00000eca0 0xc00000a380}
2019/01/19 14:10:15 Starting Init Process of Connector
[...]
2019/01/19 14:10:45 invalid character 'i' looking for beginning of value
```

**Comment by kumy** [comment] 2019-01-19 14:35
https://github.com/Templum/rabbitmq-connector/blob/bb0661c1afd1d1fb41ae15bcc2388a50b642e574/main.go#L25-L27

Isn't it the problem as for both tags `release` or `develop`, the line is always the same:

```
2019/01/19 14:35:27 OpenFaaS RabbitMQ Connector [Version: dev Commit: local]
```

**Comment by kumy** [comment] 2019-01-19 14:43
@Templum  I've built my own docker image with source code patched with _my_ credentials, and I don't encounter the problem anymore. So I think published docker images are quite unusable :/

**Comment by Templum** [comment] 2019-01-19 15:08
Thanks for the information. I will look at this then, seems to be an issue with the building pipeline

**Comment by Templum** [comment] 2019-01-19 19:06
Hey @kumy I was able to probably find the issue. Could you verify with `templum/rabbitmq-connector:hotfix_12` that it now works. As written in the documentation based on the Platform `Swarm` or `Kubernetes` you need to correctly set the credentials

**Comment by Templum** [comment] 2019-01-19 20:14
Over at #18 @kumy did verify that it now will use the correct version. I applied the hotfix to: `develop`, `release`, `latest` & `0.1.0`.

@kumy if everything works please let me know, so I can close the issue.

**Comment by kumy** [comment] 2019-01-19 20:34
@Templum I'm sorry it's not fixed in images from hub.docker.com :( version still appear as `dev` and error still raised. Tested on `templum/rabbitmq-connector:0.1.0` and `templum/rabbitmq-connector:release`

**Comment by Templum** [comment] 2019-01-19 21:04
@kumy really sorry for the inconvenience seems I pushed the wrong image by accident. Now it should work as shown by the logs

```
docker run templum/rabbitmq-connector:0.1.0
Unable to find image 'templum/rabbitmq-connector:0.1.0' locally
0.1.0: Pulling from templum/rabbitmq-connector
4fe2ade4980c: Already exists
948cc2cfc073: Pull complete
2ecc2c6a05bd: Pull complete
e694014a4775: Pull complete
Digest: sha256:ccf568038d89e81fe6a48249cfa62b68039a27366affa9c46fe78872e736fb4d
Status: Downloaded newer image for templum/rabbitmq-connector:0.1.0
&{0xc00005ad50 0xc000072320 0xc000058c80 <nil>}
2019/01/19 21:04:06 OpenFaaS RabbitMQ Connector [Version: 0.1.0 Commit: 815576e]
```

**Comment by kumy** [comment] 2019-01-19 21:10
I can confirm tag `0.1.0` is now working. @Templum Thanks!

**Closed** 2019-01-19 23:13 UTC
Labels: bug
